/aruco_node:
  ros__parameters:
    marker_size: 0.055
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /camera/camera/color/image_raw
    camera_info_topic: /camera/camera/color/camera_info

/aruco_board_node:
  ros__parameters:
    # Type of board to detect, 'aruco' or 'charuco'
    board_type: 'charuco'

    # Topics
    image_topic: /camera/camera/color/image_raw
    camera_info_topic: /camera/camera/color/camera_info
    camera_frame: "" # empty uses frame from camera_info

    # Publish the board image with markers and pose detected
    publish_board_image: true

    # Dictionary to use
    aruco_dictionary_id: DICT_5X5_250

    # --- Aruco Board Parameters ---
    #    2x2
    #    markers_x: 2
    #    markers_y: 2
    #    aruco_marker_length: 0.0314
    #    marker_separation: 0.0085
    #    3x3
    markers_x: 3
    markers_y: 3
    aruco_marker_length: 0.0189
    marker_separation: 0.00765

    # --- Charuco Board Parameters ---
    #    2x2
    #    squares_x: 2
    #    squares_y: 2
    #    square_length: 0.035
    #    charuco_marker_length: 0.021
    #    3x3
    squares_x: 3
    squares_y: 3
    square_length: 0.0235
    charuco_marker_length: 0.0141
