/aruco_node:
  ros__parameters:
    marker_size: 0.055
    aruco_dictionary_id: DICT_5X5_250
    image_topic: /image_raw
    camera_info_topic: /camera_info

/aruco_board_node:
  ros__parameters:
    # Type of board to detect, 'aruco' or 'charuco'
    board_type: 'aruco'

    # Topics
    image_topic: /image_raw
    camera_info_topic: /camera_info
    camera_frame: "" # empty uses frame from camera_info

    # Dictionary to use
    aruco_dictionary_id: DICT_5X5_250

    # --- Aruco Board Parameters ---
    # Number of markers in X and Y directions
    markers_x: 5
    markers_y: 7
    # Marker side length in meters
    marker_length: 0.04
    # Separation between markers in meters
    marker_separation: 0.01

    # --- Charuco Board Parameters ---
    # Number of squares in X and Y directions
    squares_x: 5
    squares_y: 7
    # Charuco square side length in meters
    square_length: 0.04
    # Marker side length in meters (for charuco markers)
    # The 'marker_length' parameter is shared with Aruco boards
